source "https://rubygems.org"

ruby "3.4.9"

gem "rails", "~> 7.1.3"
gem "bcrypt", "~> 3.1"
gem "pg", "~> 1.5"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "stripe", "~> 20.0"
gem "tzinfo-data", platforms: %i[windows jruby]
